plugins {
    id 'java'
    id "org.jetbrains.kotlin.jvm" version "2.2.10"
}

group = 'edu.nd.sde.hw1'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}